### ISSUE TITLE
Add code format / linting on code commit event in the repo

### ISSUE THREAD

**Issue by omeryousaf** [omeryousaf/image-editor-for-ui-feedback#32]
## Description
So far we do not have a code formatting / linting tool integrated into the project. We need to integrate some tool like eslint and also configure it to run on git commit hook so that only those commits will be accepted which have acceptable code formatting. Any code styling issues which cause a commit to fail will be reported by the tool in the terminal.

**Comment by Shapokhan** [comment]
Fixed.
